post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI2MWFiYjg4ODNmODRhMGYxZTg5MGU0NDgiLCJpYXQiOjE2Mzg2NDUzNjUsImV4cCI6MTYzODY0ODk2NX0.AZJQ1ttwHf7lrM40l114-cWw0bJznMD0By2AtVaIVqI

{
    "title": "1 user1",
    "author": "test1",
    "url": "htt///aowidjwaoidj",
    "likes": 0
} 