post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2MWFiOTFiMjA1YWEyNmM0NDcwMzY5OTYiLCJpYXQiOjE2Mzg2MzM5NzcsImV4cCI6MTYzODYzNzU3N30.UaBGqrGGmm2XHa-EXrgVXhvwNxYKxlpaXWUcFJ-RaL0

{
    "title": "Addinwadawdg New Post222",
    "author": "reama",
    "url": "htt///aowidjwaoidj",
    "likes": 2
}